### ISSUE TITLE
实现一个数组扁平化函数 flattenDepth

### ISSUE THREAD

**Issue by Tcdian** [Tcdian/keep#1]
#### 描述

```text
flattenDepth 接收两个参数，第一个参数为需要扁平化的数组，第二个参数为扁平化的深度。
```

#### Example

```javascript
var array = [1, [2, [3, [4]], 5]];
 
flattenDepth(array, 1);
// => [1, 2, [3, [4]], 5]
 
flattenDepth(array, 2);
// => [1, 2, 3, [4], 5]
```
#### solution

```javascript
function flattenDepth(array, depth = 1) {
    // todo ...
}
```

**Comment by mynameissuwei** [comment]
function flattenDeep(arr, deepLength) {
    return arr.flat(deepLength);
}

**Comment by Tcdian** [comment]
> function flattenDeep(arr, deepLength) {
> return arr.flat(deepLength);
> }

这个支持markdown语法，可以用下面这种支持js语法~
```text
```javascript
// todo ...
```
```

**Comment by fengmumu1** [comment]
```js
function flattenDepth(array = [], deep = Infinity) {
  const deepTemp = Number(deep);
  if (!Array.isArray([])) {
    console.error('Please enter an array');
    return [];
  }

  if(Number.isNaN(deepTemp) || deepTemp < 1){
    console.error('The resolution depth should be a number greater than zero');
    return array;
  }
  let deepFlage = 0;
  let resBuffer = [...array];
  while(deepFlage <= deepTemp) {
    let flage = true;
    let resTemp = [];
    resBuffer.map(item => {
      if(Array.isArray(item)){
        flage = false;
        resTemp =  [...resTemp, ...item]
      } else {
        resTemp.push(item);
      }
    });
    resBuffer = [...resTemp];
    resTemp = [];
    if(flage === true){
      return resBuffer;
    }
    deepFlage++;
  }
  return resBuffer;
}

// test
var foo = [1,2,3,[4,5], [[5,6],[[7,8,],[9,10,11]]]];
console.log('res', flattenDepth(foo, 0)) 
// (5) [1, 2, 3, Array(2), Array(2)]
console.log('res', flattenDepth(foo, 1))
// (9) [1, 2, 3, 4, 5, 5, 6, Array(2), Array(3)]
console.log('res', flattenDepth(foo, 2))
// (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
console.log('res', flattenDepth(foo))
// (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
```

**Comment by fengmumu1** [comment]
> ```js
> function flattenDepth(array = [], deep = Infinity) {
>   const deepTemp = Number(deep);
>   if (!Array.isArray([])) {
>     console.error('Please enter an array');
>     return [];
>   }
> 
>   if(Number.isNaN(deepTemp) || deepTemp < 1){
>     console.error('The resolution depth should be a number greater than zero');
>     return array;
>   }
>   let deepFlage = 0;
>   let resBuffer = [...array];
>   while(deepFlage <= deepTemp) {
>     let flage = true;
>     let resTemp = [];
>     resBuffer.map(item => {
>       if(Array.isArray(item)){
>         flage = false;
>         resTemp =  [...resTemp, ...item]
>       } else {
>         resTemp.push(item);
>       }
>     });
>     resBuffer = [...resTemp];
>     resTemp = [];
>     if(flage === true){
>       return resBuffer;
>     }
>     deepFlage++;
>   }
>   return resBuffer;
> }
> 
> // test
> var foo = [1,2,3,[4,5], [[5,6],[[7,8,],[9,10,11]]]];
> console.log('res', flattenDepth(foo, 0)) 
> // (5) [1, 2, 3, Array(2), Array(2)]
> console.log('res', flattenDepth(foo, 1))
> // (9) [1, 2, 3, 4, 5, 5, 6, Array(2), Array(3)]
> console.log('res', flattenDepth(foo, 2))
> // (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
> console.log('res', flattenDepth(foo))
> // (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
> ```

加班，撤退了，后面抽空精简&优化

**Comment by bairuobing** [comment]
```js
function flattenDepth(array, depth = 1) {
    if (depth === 0) {
        return array;
    }
    let res = [];
    array.forEach((item) => {
        if (Array.isArray(item)) {
            res = res.concat(item);
        } else {
            res.push(item);
        }
    })
    return flattenDepth(res, depth - 1);
}
```

**Comment by Tcdian** [comment]
> ```js
> function flattenDepth(array = [], deep = Infinity) {
>   const deepTemp = Number(deep);
>   if (!Array.isArray([])) {
>     console.error('Please enter an array');
>     return [];
>   }
> 
>   if(Number.isNaN(deepTemp) || deepTemp < 1){
>     console.error('The resolution depth should be a number greater than zero');
>     return array;
>   }
>   let deepFlage = 0;
>   let resBuffer = [...array];
>   while(deepFlage <= deepTemp) {
>     let flage = true;
>     let resTemp = [];
>     resBuffer.map(item => {
>       if(Array.isArray(item)){
>         flage = false;
>         resTemp =  [...resTemp, ...item]
>       } else {
>         resTemp.push(item);
>       }
>     });
>     resBuffer = [...resTemp];
>     resTemp = [];
>     if(flage === true){
>       return resBuffer;
>     }
>     deepFlage++;
>   }
>   return resBuffer;
> }
> 
> // test
> var foo = [1,2,3,[4,5], [[5,6],[[7,8,],[9,10,11]]]];
> console.log('res', flattenDepth(foo, 0)) 
> // (5) [1, 2, 3, Array(2), Array(2)]
> console.log('res', flattenDepth(foo, 1))
> // (9) [1, 2, 3, 4, 5, 5, 6, Array(2), Array(3)]
> console.log('res', flattenDepth(foo, 2))
> // (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
> console.log('res', flattenDepth(foo))
> // (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
> ```
> 
> > 加班，所以就先撤退了，后面对这个做精简&优化

你这个方法好像多展开了一层，还有没有返回值建议用forEach代替map，语义更好一点。

**Comment by fengmumu1** [comment]
> > ```js
> > function flattenDepth(array = [], deep = Infinity) {
> >   const deepTemp = Number(deep);
> >   if (!Array.isArray([])) {
> >     console.error('Please enter an array');
> >     return [];
> >   }
> > 
> >   if(Number.isNaN(deepTemp) || deepTemp < 1){
> >     console.error('The resolution depth should be a number greater than zero');
> >     return array;
> >   }
> >   let deepFlage = 0;
> >   let resBuffer = [...array];
> >   while(deepFlage <= deepTemp) {
> >     let flage = true;
> >     let resTemp = [];
> >     resBuffer.map(item => {
> >       if(Array.isArray(item)){
> >         flage = false;
> >         resTemp =  [...resTemp, ...item]
> >       } else {
> >         resTemp.push(item);
> >       }
> >     });
> >     resBuffer = [...resTemp];
> >     resTemp = [];
> >     if(flage === true){
> >       return resBuffer;
> >     }
> >     deepFlage++;
> >   }
> >   return resBuffer;
> > }
> > 
> > // test
> > var foo = [1,2,3,[4,5], [[5,6],[[7,8,],[9,10,11]]]];
> > console.log('res', flattenDepth(foo, 0)) 
> > // (5) [1, 2, 3, Array(2), Array(2)]
> > console.log('res', flattenDepth(foo, 1))
> > // (9) [1, 2, 3, 4, 5, 5, 6, Array(2), Array(3)]
> > console.log('res', flattenDepth(foo, 2))
> > // (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
> > console.log('res', flattenDepth(foo))
> > // (12) [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11]
> > ```
> > 
> > 
> > > 加班，所以就先撤退了，后面对这个做精简&优化
> 
> 你这个方法好像多展开了一层，还有没有返回值建议用forEach代替map，语义更好一点。

- 没有吧，给 1 的时候只展开了一层啊
- 刚才路上想了一下，优化的方向还是用递归做，这里多次判断了，
- react 写多了，循环首先想到的就是 map，刚才在工位头快炸了，上一位给我留下不少坑

**Comment by fengmumu1** [comment]
> ```js
> function flattenDepth(array, depth = 1) {
>     if (depth === 0) {
>         return array;
>     }
>     let res = [];
>     array.forEach((item) => {
>         if (Array.isArray(item)) {
>             res = res.concat(item);
>         } else {
>             res.push(item);
>         }
>     })
>     return flattenDepth(res, depth - 1);
> }
> ```

看过一个文章说 解构运算符 比 concat 效率更高

**Comment by Tcdian** [comment]
刚刚学TypeScript，试着用TypeScript写一写
```typescript
interface RecursiveArray<T> extends Array<T|RecursiveArray<T>> {}

function flattenDepth<T>(array: RecursiveArray<T>, depth: number = 1): RecursiveArray<T> {
    let flatOneDepthArray = [] as RecursiveArray<T>;
    array.forEach((item) => {
        if (depth > 0 && Array.isArray(item)) {
            flatOneDepthArray = [...flatOneDepthArray, ...flattenDepth(item, depth - 1)];
        } else {
            flatOneDepthArray = [...flatOneDepthArray, item];
        }
    });
    return flatOneDepthArray;
}
```

**Comment by fengmumu1** [comment]
> 刚刚学TypeScript，试着用TypeScript写一写
> 
> ```ts
> interface RecursiveArray<T> extends Array<T|RecursiveArray<T>> {}
> 
> function flattenDepth<T>(array: RecursiveArray<T>, depth: number = 1): RecursiveArray<T> {
>     let result = [] as RecursiveArray<T>;
>     array.forEach((item) => {
>         if (depth > 0 && Array.isArray(item)) {
>             result = [...result, ...flattenDepth(item, depth - 1)];
>         } else {
>             result = [...result, item];
>         }
>     });
>     return result;
> }
> ```
```js
    array.forEach((item) => {
        if (depth > 0 && Array.isArray(item)) {
            result = [...result, ...flattenDepth(item, depth - 1)];
        } else {
            result = [...result, item];
        }
    });
```
这里如果 deep  已经是小于等于0了，就可以直接返回了，不用做一遍遍历和结构

**Comment by fengmumu1** [comment]
这个题目没有给出结果啊，我觉得从简单高效上看，应该使用递归，针对每一个元素做递归，然后如果递归层级到了扩展层级就返回就可以了，如果某个元素在层级范围内已经不可展开也可以直接返回了，然后入参做一下校验，小于等于1 的时候直接返回结果

**Comment by fengmumu1** [comment]
> 这个题目没有给出结果啊，我觉得从简单高效上看，应该使用递归，针对每一个元素做递归，然后如果递归层级到了扩展层级就返回就可以了，如果某个元素在层级范围内已经不可展开也可以直接返回了，然后入参做一下校验，小于等于1 的时候直接返回结果

代码，没有代码，写Bug去啦
