### ISSUE TITLE
Context Example

### ISSUE THREAD

**Issue by Tcdian** [Tcdian/keep#6]

**Comment by Tcdian** [comment]
- 使用 useReducer , useContext , 实现多个组件间数据共享。 [代码参考](https://github.com/Tcdian/black/tree/master/src/components/demo/stateManagement)

**Comment by fengmumu1** [comment]
> ### 使用 useReducer , useContext , 实现多个组件间数据共享。
> * [代码参考](https://github.com/Tcdian/black/tree/master/src/components/demo/stateManagement)

为啥代码在另一个库里，都搞到一个文件里呗
