### ISSUE TITLE
群里小姐姐的那个问题，收纳进来怎么样

### ISSUE THREAD

**Issue by fengmumu1** [Tcdian/keep#8]
![目标](https://user-images.githubusercontent.com/37215225/63254172-d4f92180-c2a5-11e9-924c-4389549f3107.gif)
xi效果我录成动图了
渲染一个树状结构，节点可以拖拽，实现以下特性
0.节点可以展开/收缩
1.将S从上/下方拖过上一个节点T的中位线时，S节点占位移动到T节点的位置。
2.将S节点拖入T节点20%-50%或50%-80%位置区间，但未穿过50%时，如果停留时间超过0.5秒，则将S节点加入T的子节点，并展开T节点。
3.当用户释放正在拖拽的S节点时，调整节点从属关系。
要求所有视觉由流畅的动画表现。请梳理其中数据流关系。

**Comment by Tcdian** [comment]
你确定要用前端实现这个效果，需要写很多css代码和操作dom的代码，而且这种前端的适用面很窄吧，页面中会有这么繁杂的操作吗，这个不是类似vscode目录的东西~ @fengmumu1

**Comment by fengmumu1** [comment]
> 而且这种前端的适用面很窄吧，页面中会有这么繁杂的操作吗，这个不是类似vscode目录的东西

- 嗯，是这样的，撇开css和效果不说，实现这个，对于拖拽的操作和dome的操作是由一定的要求的，至于动画效果，说真的，我个人是比较讨厌的，因为所谓的动画效果更改了dome，我用的是框架，而现代框架核心就是数据驱动dome，而题目的意思也是使用框架的，撇开这个不谈，树形的结构数据如何安排，如果加上存储如何安排，可能整个项目不会再实际中用到，但是牵扯到的东西在实际中还是会用到的
- 还有就是，我个人理解的这个项目是有各种好玩有趣的知识点，知识点或难，或生僻，或有趣，当作面试题也好，知识点的扩充也好，每一道题应该有其核心点，或者收获点，我觉得满足这个就可以吧，或者以后题目本身就打上标签，分一些类，比如，面试，算法，杂谈，综合什么的

**Comment by Tcdian** [comment]
> > 而且这种前端的适用面很窄吧，页面中会有这么繁杂的操作吗，这个不是类似vscode目录的东西
> 
> * 嗯，是这样的，撇开css和效果不说，实现这个，对于拖拽的操作和dome的操作是由一定的要求的，至于动画效果，说真的，我个人是比较讨厌的，因为所谓的动画效果更改了dome，我用的是框架，而现代框架核心就是数据驱动dome，而题目的意思也是使用框架的，撇开这个不谈，树形的结构数据如何安排，如果加上存储如何安排，可能整个项目不会再实际中用到，但是牵扯到的东西在实际中还是会用到的
> * 还有就是，我个人理解的这个项目是有各种好玩有趣的知识点，知识点或难，或生僻，或有趣，当作面试题也好，知识点的扩充也好，每一道题应该有其核心点，或者收获点，我觉得满足这个就可以吧，或者以后题目本身就打上标签，分一些类，比如，面试，算法，杂谈，综合什么的

但是我弄这个的目的，并不是为了猎奇，是为了写代码，收集人人都会，就这个题目，你会去写吗？就算写了，你要花多久的时间去写，这样就违背了这种小的知识点的意思，我当时就想过这个问题，我想要的不是大而全，而是细分的点~

**Comment by Tcdian** [comment]
> > 而且这种前端的适用面很窄吧，页面中会有这么繁杂的操作吗，这个不是类似vscode目录的东西
> 
> * 嗯，是这样的，撇开css和效果不说，实现这个，对于拖拽的操作和dome的操作是由一定的要求的，至于动画效果，说真的，我个人是比较讨厌的，因为所谓的动画效果更改了dome，我用的是框架，而现代框架核心就是数据驱动dome，而题目的意思也是使用框架的，撇开这个不谈，树形的结构数据如何安排，如果加上存储如何安排，可能整个项目不会再实际中用到，但是牵扯到的东西在实际中还是会用到的
> * 还有就是，我个人理解的这个项目是有各种好玩有趣的知识点，知识点或难，或生僻，或有趣，当作面试题也好，知识点的扩充也好，每一道题应该有其核心点，或者收获点，我觉得满足这个就可以吧，或者以后题目本身就打上标签，分一些类，比如，面试，算法，杂谈，综合什么的

要不重新搞个收集的吧，这个反正也没别人写了，我把这个当作平时工作，学习遇到的问题的记录，可能今天我就刷了个算法题，我感觉这题目比较好，我把它记录下，整理下~

**Comment by fengmumu1** [comment]
> 这个反正也没别人写了，我把这个当作平时工作，学习遇到的问题的记录，可能今天我就刷了个算法题，我感觉这题目比较好，我把它记录下，整理下~

也是，基本就第一天都参与了以下，后面基本凉凉了

**Comment by fengmumu1** [comment]
> > > 而且这种前端的适用面很窄吧，页面中会有这么繁杂的操作吗，这个不是类似vscode目录的东西
> > 
> > 
> > 
> > * 嗯，是这样的，撇开css和效果不说，实现这个，对于拖拽的操作和dome的操作是由一定的要求的，至于动画效果，说真的，我个人是比较讨厌的，因为所谓的动画效果更改了dome，我用的是框架，而现代框架核心就是数据驱动dome，而题目的意思也是使用框架的，撇开这个不谈，树形的结构数据如何安排，如果加上存储如何安排，可能整个项目不会再实际中用到，但是牵扯到的东西在实际中还是会用到的
> > * 还有就是，我个人理解的这个项目是有各种好玩有趣的知识点，知识点或难，或生僻，或有趣，当作面试题也好，知识点的扩充也好，每一道题应该有其核心点，或者收获点，我觉得满足这个就可以吧，或者以后题目本身就打上标签，分一些类，比如，面试，算法，杂谈，综合什么的
> 
> 但是我弄这个的目的，并不是为了猎奇，是为了写代码，收集人人都会，就这个题目，你会去写吗？就算写了，你要花多久的时间去写，这样就违背了这种小的知识点的意思，我当时就想过这个问题，我想要的不是大而全，而是细分的点~

其实关于小的知识点，我觉得还是要引入分类，不然数目以多就看起来很分散，至于说是猎奇什么的，嗯，咋说，这个每个人见解不一样，对了上面那个我实现啦，大概用了两个晚上吧
https://codepen.io/fengmumu1/pen/aboNwWd

**Comment by Tcdian** [comment]
> > > > 而且这种前端的适用面很窄吧，页面中会有这么繁杂的操作吗，这个不是类似vscode目录的东西
> > > 
> > > 
> > > 
> > > * 嗯，是这样的，撇开css和效果不说，实现这个，对于拖拽的操作和dome的操作是由一定的要求的，至于动画效果，说真的，我个人是比较讨厌的，因为所谓的动画效果更改了dome，我用的是框架，而现代框架核心就是数据驱动dome，而题目的意思也是使用框架的，撇开这个不谈，树形的结构数据如何安排，如果加上存储如何安排，可能整个项目不会再实际中用到，但是牵扯到的东西在实际中还是会用到的
> > > * 还有就是，我个人理解的这个项目是有各种好玩有趣的知识点，知识点或难，或生僻，或有趣，当作面试题也好，知识点的扩充也好，每一道题应该有其核心点，或者收获点，我觉得满足这个就可以吧，或者以后题目本身就打上标签，分一些类，比如，面试，算法，杂谈，综合什么的
> > 
> > 
> > 但是我弄这个的目的，并不是为了猎奇，是为了写代码，收集人人都会，就这个题目，你会去写吗？就算写了，你要花多久的时间去写，这样就违背了这种小的知识点的意思，我当时就想过这个问题，我想要的不是大而全，而是细分的点~
> 
> 其实关于小的知识点，我觉得还是要引入分类，不然数目以多就看起来很分散，至于说是猎奇什么的，嗯，咋说，这个每个人见解不一样，对了上面那个我实现啦，大概用了两个晚上吧
> https://codepen.io/fengmumu1/pen/aboNwWd

好吧，你说的有理，反正我是不会自己去写一个这这种东西的，你自己去搞一个收集吧，我这边可能后面会涉及很多算法的，因为可能工作中遇不到什么，我就会写一个leetcode~我要把issue关掉了~
